version: "3.8"

volumes:
  postgres_data:

networks:
  shop:

services:
  avito-shop-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/avito-shop/logs/
      - ./migrations:/avito-shop/source/migrations
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - shop

  postgres:
    image: postgres:16.2-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - shop